# Generated by Django 5.0.7 on 2026-04-26 08:45

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("side", models.CharField(max_length=4)),
                ("price", models.DecimalField(decimal_places=9, max_digits=20)),
                ("quantity", models.DecimalField(decimal_places=9, max_digits=20)),
                ("exchange_id", models.CharField(db_index=True, max_length=50)),
                ("trade_id", models.CharField(max_length=100, unique=True)),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=20, null=True
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=5
                    ),
                ),
                ("is_high_risk", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
